# Generated by Django 5.0.1 on 2024-01-28 08:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0004_alter_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canelation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthDate',
            field=models.ForeignKey(default=datetime.date(2024, 1, 28), on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='clinic_management.tdate'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='surname',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
