# Generated by Django 5.0.1 on 2024-01-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0005_appointment_canelation_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='canelation',
            new_name='canellation',
        ),
    ]
