# Generated by Django 5.0.1 on 2024-01-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0006_rename_canelation_appointment_canellation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='canellation',
            new_name='cancellation',
        ),
    ]
