# Generated by Django 5.0.1 on 2024-01-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0007_rename_canellation_appointment_cancellation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cancellation',
            new_name='cancellated',
        ),
    ]
